version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:14.10.1
    steps:
      - checkout
      - runs:
          command: npm install
      - runs:
          command: npm test
                